# Generated by Django 4.2.6 on 2023-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('address1', models.TextField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('landline_no', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Noida', 'Noida'), ('Lucknow', 'Lucknow')], max_length=18)),
                ('address2', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('gstno', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'customtb',
            },
        ),
    ]
